{!!Html::script('public/adminLTE/plugins/jQuery/jquery-migrate-1.2.1.min.js')!!}
{!!Html::script('public/adminLTE/plugins/WOW/dist/wow.min.js')!!}
{!!Html::script('public/adminLTE/plugins/notify/bootstrap-notify.min.js')!!}
{!!Html::script('public/adminLTE/dist/js/customajax.js')!!}
{!!Html::script('public/adminLTE/dist/js/customapp.js')!!}
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>

{!!Html::script('public/adminLTE/bootstrap/js/bootstrap.min.js')!!}
{!!Html::script('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')!!}
{!!Html::script('public/adminLTE/plugins/morris/morris.min.js')!!}
{!!Html::script('public/adminLTE/plugins/sparkline/jquery.sparkline.min.js')!!}
{!!Html::script('public/adminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')!!}
{!!Html::script('public/adminLTE/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')!!}
{!!Html::script('public/adminLTE/plugins/knob/jquery.knob.js')!!}
{!!Html::script('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js')!!}
{!!Html::script('public/adminLTE/plugins/daterangepicker/daterangepicker.js')!!}
{!!Html::script('public/adminLTE/plugins/datepicker/bootstrap-datepicker.js')!!}
{!!Html::script('public/adminLTE/plugins/datatables-2/datatables.net/js/jquery.dataTables.min.js')!!}
{!!Html::script('public/adminLTE/plugins/datatables-2/datatables.net-bs/js/dataTables.bootstrap.min.js')!!}
{!!Html::script('public/adminLTE/plugins/datatables-2/datatables.net-buttons/js/dataTables.buttons.min.js')!!}
{!!Html::script('public/adminLTE/plugins/datatables-2/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')!!}
{!!Html::script('public/adminLTE/plugins/datatables-2/datatables.net-buttons/js/buttons.flash.min.js')!!}
{!!Html::script('public/adminLTE/plugins/datatables-2/datatables.net-buttons/js/buttons.colVis.min.js')!!}
{!!Html::script('public/adminLTE/plugins/datatables-2/datatables.net-buttons/js/buttons.html5.min.js')!!}
{!!Html::script('public/adminLTE/plugins/datatables-2/datatables.net-buttons/js/buttons.print.min.js')!!}
{!!Html::script('public/adminLTE/plugins/slimScroll/jquery.slimscroll.min.js')!!}
{!!Html::script('public/adminLTE/plugins/fastclick/fastclick.min.js')!!}
{!!Html::script('public/adminLTE/plugins/slick/slick.min.js')!!}
{!!Html::script('public/adminLTE/plugins/animatescroll/animatescroll.min.js')!!}
{!!Html::script('public/adminLTE/plugins/animsition/dist/js/animsition.js')!!}
{!!Html::script('public/adminLTE/plugins/simple-pagination/jquery.simplePagination.js')!!}
{!!Html::script('public/adminLTE/plugins/fileinput/js/fileinput.min.js')!!}
{!!Html::script('public/adminLTE/dist/js/app.min.js')!!}
{!!Html::script('public/adminLTE/dist/js/pages/dashboard.js')!!}
{!!Html::script('public/adminLTE/dist/js/demo.js')!!}
{!!Html::script('public/adminLTE/plugins/validator/dist/js/bootstrapValidator.min.js')!!}

