{{ Html::style('public/adminLTE/dist/img/logo.png', array('rel' => 'shortcut icon')) }}
{!!Html::style('public/adminLTE/bootstrap/css/bootstrap.css')!!}
{!!Html::style('public/adminLTE/plugins/notify/animate.css')!!}
{!!Html::style('public/adminLTE/plugins/font-awesome-4.5.0/css/font-awesome.min.css')!!}
{!!Html::style('public/adminLTE/plugins/ionicons-master/css/ionicons.min.css')!!}
{{--{!!Html::style('public/adminLTE/plugins/daterangepicker/daterangepicker.css')!!}--}}
{!!Html::style('public/adminLTE/plugins/datatables-2/datatables.net-dt/css/jquery.dataTables.css')!!}
{!!Html::style('public/adminLTE/plugins/datatables-2/datatables.net-bs/css/dataTables.bootstrap.min.css')!!}
{!!Html::style('public/adminLTE/plugins/datatables-2/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')!!}
{!!Html::style('public/adminLTE/plugins/fileinput/css/fileinput.css')!!}
{{--{!!Html::style('public/adminLTE/plugins/morris/morris.css')!!}--}}
{!!Html::style('public/adminLTE/dist/css/adminLTE.css')!!}
{!!Html::style('public/adminLTE/dist/css/skins/skin-white.css')!!}
{{--{!!Html::style('public/adminLTE/dist/css/skins/_all-skins.min.css')!!}--}}
{!!Html::style('public/adminLTE/plugins/slick/slick.css')!!}
{!!Html::style('public/adminLTE/plugins/slick/slick-theme.css')!!}
{!!Html::style('public/adminLTE/plugins/animsition/dist/css/animsition.css')!!}
{!!Html::style('public/adminLTE/plugins/simple-pagination/simplePagination.css')!!}
{{--{!!Html::style('public/adminLTE/plugins/fileinput/css/fileinput.min.css')!!}--}}
{!!Html::style('public/adminLTE/dist/css/vertical-carousel.css')!!}
{!!Html::style('public/adminLTE/plugins/validator/dist/css/bootstrapValidator.css')!!}